<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ie.bitstep.mango.workshop.talk</groupId>
        <artifactId>mango4j-crypto-workshop-talk</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>mango4j-crypto-workshop-talk-naive-single-hmac</artifactId>
    <packaging>jar</packaging>
    <name>Mango4j Crypto ALE Workshop - The Talk: Naive Single HMAC</name>

    <properties>
        <exec.mainClass>ie.bitstep.mango.workshop.talk.naivesinglehmac.Main</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <mainClass>${exec.mainClass}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
